[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'

[tool.ruff.lint]
# Pyflakes
select = ["F"]

# Not working, don't know why
[tool.ruff.lint.flake8-implicit-str-concat]
allow-multiline = false
